version: "3.3"

services:
  dzielo-biblijne-cms:
    image: $IMAGE:latest
    container_name: dzielo-biblijne-cms
    environment:
      NODE_ENV: production
      DATABASE_HOST: dzielo-biblijne-db
      DATABASE_NAME: $DB_NAME
      DATABASE_USERNAME: $DB_USERNAME
      DATABASE_PASSWORD: $DB_PASSWORD
      DATABASE_PORT: 27017
      AUTHENTICATION_DATABASE: $AUTH_DB
    tty: true
    restart: always
    ports:
      - $APP_PORT:1337
    volumes:
      - $MEDIA_VOLUME_PATH:/src/app/public/uploads

  dzielo-biblijne-db:
    image: mongo:5.0.6
    container_name: dzielo-biblijne-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - $DB_VOLUME_PATH:/data/db
    restart: unless-stopped
